-- MySQL Script generated by MySQL Workbench
-- Sat Jul 17 11:55:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oc-pizza
-- -----------------------------------------------------
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Client` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Client` (
  `idClient` INT NOT NULL,
  `e-mail` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `mot de passe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Adresse` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Adresse` (
  `refAdresse` INT NOT NULL,
  `numero` INT UNSIGNED NOT NULL,
  `rue` VARCHAR(45) NOT NULL,
  `ville` VARCHAR(3) NOT NULL,
  `codePostal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`refAdresse`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Commande` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Commande` (
  `idCommande` INT NOT NULL,
  `dateCommande` DATETIME NOT NULL,
  `valeurPanier` DOUBLE NOT NULL,
  `reduction` DOUBLE NULL,
  `livraison` TINYINT NOT NULL DEFAULT 1,
  `Adresse_refAdresse` INT NOT NULL,
  PRIMARY KEY (`idCommande`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Commande_Adresse1_idx` ON `Commande` (`Adresse_refAdresse` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Notification` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Notification` (
  `refNotif` INT NOT NULL,
  `créeLe` DATETIME NULL,
  `maj` DATETIME NULL,
  PRIMARY KEY (`refNotif`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Notification_has_Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Notification_has_Client` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Notification_has_Client` (
  `Notification_refNotif` INT NOT NULL,
  `Client_idClient` INT NOT NULL,
  PRIMARY KEY (`Notification_refNotif`, `Client_idClient`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Notification_has_Client_Client1_idx` ON `Notification_has_Client` (`Client_idClient` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Notification_has_Client_Notification1_idx` ON `Notification_has_Client` (`Notification_refNotif` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Client_has_Commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Client_has_Commande` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Client_has_Commande` (
  `Client_idClient` INT NOT NULL,
  `Commande_idCommande` INT NOT NULL,
  PRIMARY KEY (`Client_idClient`, `Commande_idCommande`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Client_has_Commande_Commande1_idx` ON `Client_has_Commande` (`Commande_idCommande` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Client_has_Commande_Client1_idx` ON `Client_has_Commande` (`Client_idClient` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Statut Commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Statut Commande` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Statut Commande` (
  `idStatut Commande` INT NOT NULL,
  `etatCreation` DATETIME NULL,
  `etatPaiement` TINYINT NULL,
  `etatPreparation` DATETIME NULL,
  `etatLivraison` DATETIME NULL,
  PRIMARY KEY (`idStatut Commande`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Notification_has_Statut Commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Notification_has_Statut Commande` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Notification_has_Statut Commande` (
  `Notification_refNotif` INT NOT NULL,
  `Statut Commande_idStatut Commande` INT NOT NULL,
  PRIMARY KEY (`Notification_refNotif`, `Statut Commande_idStatut Commande`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Notification_has_Statut Commande_Statut Commande1_idx` ON `Notification_has_Statut Commande` (`Statut Commande_idStatut Commande` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Notification_has_Statut Commande_Notification1_idx` ON `Notification_has_Statut Commande` (`Notification_refNotif` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Commande_has_Statut Commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Commande_has_Statut Commande` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Commande_has_Statut Commande` (
  `Commande_idCommande` INT NOT NULL,
  `Statut Commande_idStatut Commande` INT NOT NULL,
  PRIMARY KEY (`Commande_idCommande`, `Statut Commande_idStatut Commande`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Commande_has_Statut Commande_Statut Commande1_idx` ON `Commande_has_Statut Commande` (`Statut Commande_idStatut Commande` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Commande_has_Statut Commande_Commande1_idx` ON `Commande_has_Statut Commande` (`Commande_idCommande` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Employé`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employé` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Employé` (
  `idEmployé` INT NOT NULL,
  `refCommande` VARCHAR(45) CHARACTER SET 'DEFAULT' NULL,
  `fonction` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmployé`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Restaurant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurant` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Restaurant` (
  `refRestaurant` INT NOT NULL,
  `refAdresse` VARCHAR(45) NULL,
  `refNotif` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `nombre employés` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NULL,
  `faq` VARCHAR(45) NULL,
  `Commande_idCommande` INT NOT NULL,
  `Employé_idEmployé` INT NOT NULL,
  `Adresse_refAdresse` INT NOT NULL,
  PRIMARY KEY (`refRestaurant`, `Commande_idCommande`, `Employé_idEmployé`, `Adresse_refAdresse`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Restaurant_Commande1_idx` ON `Restaurant` (`Commande_idCommande` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Restaurant_Employé1_idx` ON `Restaurant` (`Employé_idEmployé` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Restaurant_Adresse1_idx` ON `Restaurant` (`Adresse_refAdresse` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Commande_has_Employé`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Commande_has_Employé` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Commande_has_Employé` (
  `Commande_idCommande` INT NOT NULL,
  `Employé_idEmployé` INT NOT NULL,
  PRIMARY KEY (`Commande_idCommande`, `Employé_idEmployé`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Commande_has_Employé_Employé1_idx` ON `Commande_has_Employé` (`Employé_idEmployé` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Commande_has_Employé_Commande1_idx` ON `Commande_has_Employé` (`Commande_idCommande` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Restaurant_has_Employé`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Restaurant_has_Employé` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Restaurant_has_Employé` (
  `Restaurant_refRestaurant` INT NOT NULL,
  `Restaurant_Commande_idCommande` INT NOT NULL,
  `Restaurant_Employé_idEmployé` INT NOT NULL,
  `Employé_idEmployé` INT NOT NULL,
  PRIMARY KEY (`Restaurant_refRestaurant`, `Restaurant_Commande_idCommande`, `Restaurant_Employé_idEmployé`, `Employé_idEmployé`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Restaurant_has_Employé_Employé1_idx` ON `Restaurant_has_Employé` (`Employé_idEmployé` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Restaurant_has_Employé_Restaurant1_idx` ON `Restaurant_has_Employé` (`Restaurant_refRestaurant` ASC, `Restaurant_Commande_idCommande` ASC, `Restaurant_Employé_idEmployé` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Employé_has_Notification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employé_has_Notification` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Employé_has_Notification` (
  `Employé_idEmployé` INT NOT NULL,
  `Notification_refNotif` INT NOT NULL,
  PRIMARY KEY (`Employé_idEmployé`, `Notification_refNotif`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Employé_has_Notification_Notification1_idx` ON `Employé_has_Notification` (`Notification_refNotif` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Employé_has_Notification_Employé1_idx` ON `Employé_has_Notification` (`Employé_idEmployé` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Recettes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Recettes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Recettes` (
  `idrecettes` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `tempsEstimé` DATETIME NULL,
  PRIMARY KEY (`idrecettes`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Employé_has_Recettes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employé_has_Recettes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Employé_has_Recettes` (
  `Employé_idEmployé` INT NOT NULL,
  `Recettes_idrecettes` INT NOT NULL,
  PRIMARY KEY (`Employé_idEmployé`, `Recettes_idrecettes`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Employé_has_Recettes_Recettes1_idx` ON `Employé_has_Recettes` (`Recettes_idrecettes` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Employé_has_Recettes_Employé1_idx` ON `Employé_has_Recettes` (`Employé_idEmployé` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Employé_has_Adresse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employé_has_Adresse` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Employé_has_Adresse` (
  `Employé_idEmployé` INT NOT NULL,
  `Adresse_refAdresse` INT NOT NULL,
  PRIMARY KEY (`Employé_idEmployé`, `Adresse_refAdresse`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Employé_has_Adresse_Adresse1_idx` ON `Employé_has_Adresse` (`Adresse_refAdresse` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Employé_has_Adresse_Employé1_idx` ON `Employé_has_Adresse` (`Employé_idEmployé` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Statut Commande_has_Employé`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Statut Commande_has_Employé` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Statut Commande_has_Employé` (
  `Statut Commande_idStatut Commande` INT NOT NULL,
  `Employé_idEmployé` INT NOT NULL,
  PRIMARY KEY (`Statut Commande_idStatut Commande`, `Employé_idEmployé`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Statut Commande_has_Employé_Employé1_idx` ON `Statut Commande_has_Employé` (`Employé_idEmployé` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Statut Commande_has_Employé_Statut Commande1_idx` ON `Statut Commande_has_Employé` (`Statut Commande_idStatut Commande` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Matières premières`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Matières premières` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Matières premières` (
  `idMatières premières` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `refonteStock` DATETIME NULL,
  `maj` DATETIME NULL,
  PRIMARY KEY (`idMatières premières`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Employé_has_Matières premières`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employé_has_Matières premières` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Employé_has_Matières premières` (
  `Employé_idEmployé` INT NOT NULL,
  `Matières premières_idMatières premières` INT NOT NULL,
  PRIMARY KEY (`Employé_idEmployé`, `Matières premières_idMatières premières`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Employé_has_Matières premières_Matières premières1_idx` ON `Employé_has_Matières premières` (`Matières premières_idMatières premières` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Employé_has_Matières premières_Employé1_idx` ON `Employé_has_Matières premières` (`Employé_idEmployé` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Ingrédients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ingrédients` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Ingrédients` (
  `idIngrédients` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `refonteStock` DATETIME NULL,
  `maj` DATETIME NULL,
  PRIMARY KEY (`idIngrédients`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Employé_has_Ingrédients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employé_has_Ingrédients` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Employé_has_Ingrédients` (
  `Employé_idEmployé` INT NOT NULL,
  `Ingrédients_idIngrédients` INT NOT NULL,
  PRIMARY KEY (`Employé_idEmployé`, `Ingrédients_idIngrédients`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Employé_has_Ingrédients_Ingrédients1_idx` ON `Employé_has_Ingrédients` (`Ingrédients_idIngrédients` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_Employé_has_Ingrédients_Employé1_idx` ON `Employé_has_Ingrédients` (`Employé_idEmployé` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
